### PR TITLE
feat: create pdf format 

### PR DESCRIPTION
**Pull request by Abdulrasheed1729**

### CODE REVIEW

**Comment by Abdulrasheed1729** [comment]
Will keep updating the pdf with commits on each sections

**Comment by Abdulrasheed1729** [comment]
Later found out that [pandoc](https://pandoc.org/) is easier and faster for converting markdown to pdf

**Review by Yczar — COMMENTED** [review]
**General Feedback**
First off, great job on taking this initiative - it is much appreciated.

**Issues Identified**
* PDF Loading Issue
**Description**: The PDF document does not load past page 25 during my review. This might be an issue stemming from my internet connection, but it might be worth looking into to ensure that other reviewers/users do not encounter the same problem.
**Suggested Action**: Could we investigate if the issue persists on different networks and browsers to rule out the possibility of it being an internet issue?

* Author Credits
**Description**: Currently, there isn't a dedicated section to acknowledge the contributions of the various authors involved in the project.
**Suggested Action**: Could we add an “Authors' Credit” page or section to appropriately recognize the individuals involved in the crafting of the content?

**Comment by Abdulrasheed1729** [comment]
Thanks for your feedback.
- **PDF Loading issue**
I noticed some errors in the generated [Pandoc](https://pandoc.org) PDF, so the loading issue is not due to network, I also investigated with Firefox and Libre Wolf and got the same result. So, in that note, I decide not to use [Pandoc](https://pandoc.org) again, I will just use the Vanilla LaTeX instead of generating codes.

- **Author Credits**
Yes, that will be nice.

**Comment by Abdulrasheed1729** [comment]
The PDF in d1112a9 contains from chapter 1 through 3, and it loads perfectly :smile:

**Comment by Yczar** [comment]
Awesome, I love this!!!

Merging in a bit

**Review by Yczar — APPROVED** [review]

**Pull request merged**
